# Generated by Django 4.2.6 on 2023-10-30 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_rename_user_application_application_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['created']},
        ),
    ]
